### ISSUE TITLE
Add StatHat tracking

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/DSMemberCounter#6]
Would be useful to know what and when the DSMemberCounter sends to the Drupal API, to help troubleshoot any outages or weird behavior.

cc @barryclark @DeeZone

**Comment by deadlybutter** [comment]
This app is being deprecated and moved into the new Dashboard to help simplify things, I'll add this issue in that repo 

https://github.com/DoSomething/DS-Realtime-Feed/issues/95
